# Generated by Django 4.1.5 on 2023-01-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=66)),
                ('last_name', models.CharField(max_length=65)),
                ('role', models.CharField(max_length=99)),
                ('dept', models.CharField(max_length=99)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
